### ISSUE TITLE
Flexible learning steps

### ISSUE THREAD

**Issue by ijgnd** [lovac42/PimsleurEmulator#1]
First of all: Thanks for another great add-on.

Since I didn't find another way of contacting you directly may I post an unrelated idea here? 

You are probably the add-on author with the best knowledge of Anki's scheduler. For other add-ons other people suggested features and you implemented them if you liked these. So I post about a thing that has bothered me about Anki for a long time. Maybe there is a tiny chance that you might like it. Maybe it'll be relevant if you ever run out of ideas for Anki add-ons but are still motivated to write an add-on ...  If you don't like this idea - just delete this thread. This post is not about "ordering" an add-on but more of trying to put an idea in your head that hopefully in the long term sounds interesting for you. Anyway, thanks for your attention/time and (in advance) sorry for such a brazen post. 

**flexible learning steps**

When I learn difficult new cards I usually need more reviews than the default "1 10" minutes - usually I need at least an additional review about one hour later (and if I don't learn at night) one review about 4-6 hours later. So I usually use "5 50 250" or otherwise I forget about 1/2 of my new cards.

I have three problems with Anki when learning new cards:

1. Quite often I don't have time to use Anki on my computer or smartphone at the appropriate time (like 50 minutes after learning a couple of new cards). So when I come back to Anki I usually have learning cards that are "overdue". I forget a lot of these cards (as expected) but usually I remember about 1/2 of these cards even though the actual interval was much larger than the learning step. It would save time and nerves if the next learning step would take the actual prior interval into account. 

   Example 1: I have seen a card once and rated it as good at 08:00. Then (given that my learning steps are "1 10 50 250") the card will be scheduled for 08:10. But for some reason I can only do the review at 8:40 wich is 40min after the review. Then I would see the options "Again (1m) - Good (50m) - Easy (1d = my Easy Interval)". If I remember the card at that time the interval for good should be much longer. Maybe it it should be calculated like this (?): "Incremental factor in my learning steps (50min/10min = 5)" times "the actual interval": 5 * 40 = 200. I don't know what this would mean for the next learning step. Probably it should be adjusted similarly. Alternatively: 200 is much closer to the learning step of 250 than to the actual learning step of 50. So maybe 50 should be skipped? 

   Example 2: I have seen a card once and rated it as good at 08:00. Then (given that my learning steps are "5 50 250") the card will be scheduled for 08:50. But for some reason I can only do the review at 11:00 wich is 180min later. Then I would see the options "Again (5m) - Good (250m) - Easy (1d = my Easy Interval)". If I remember the card at that time the interval for good should probably be according to the formula mentioned aboive: 5 * 180 = 900. The next review would be due at 3:00 in the morning of the next day. This is past my "next day starts at setting" so the due date is during the same day it would be if I had done all the learning steps. So the card should be graduated immediately.

2. There should be an option that Anki takes the interval between card creation and first viewing of a card into account: I don't like shared deck and making cards is an important part of learning for me. Let's say I have these learning steps "1 10 100" and I create a card at 14:00. The first time I see this card I will get the options "Again (1m) - Good (10m) - Easy (1d = my Easy Interval)". These options fit if see the card the first time at 14:01. Then an interval of 10 minutes is appropriate. But maybe I create new notes for about 20 minutes without interruptions so that I see the card for the first time at 14:20? Then the good interval that Anki offers is too small.

3. Some cards are easier to remember than other cards. Only the latter need these additional reviews. I could try to fix this problem by putting my cards into two different decks that have different learning steps. But my problem is that when creating a card I often don't know if I have trouble remembering this card - I only find out when I see the cards which cards are hard for me (even though I have created thousands of cards over the years). So I would have to change the deck during review which at the moment is too time-consuming. At the moment I must either see too many learning cards or deal with many failed learning cards. 

Personally I would prefer a radically different solution for learning steps that uses these settings:  "initial good interval in minutes", "multiplier for good", "multiplier for easy", "graduating threshold in minutes". This should be somewhat similar to the settings of Anki 1.2 where I could choose the initital values for each button. But this would only work for people like me who use learning steps that increase by a constant factor .... 

Did I miss some obvious work around for this? Is this just a pseudo problem? 

In the summer I tried to implement this different solution. I postponed the project because my programming knowledge is too limited. The code doesn't work in all cases and is very ugly, see [here](https://gist.github.com/ijgnd/fe9427bb316c9441fc1eb82f7e032582).

Thanks again for your time and sorry for inconveniencing you with such a post.

**Comment by ijgnd** [comment]
I just saw the code "PimsleurEmulator". I could only glance at it but with a START_VAL, MULT, ADJUST_FOR_OVERDUE it seems very very close to my idea. Thank you !!! I will carefully look at it over the next weeks. After this delayed answer I think I should't use shorter time frames ...

Sorry for answering so late. I have no excuse - just an explanation: Your criticism of learning steps made me question my learning strategy. Over the last two weeks I experimented with different content in Anki and also with supermemo which doesn't offer learning steps. Figuring out how supermemo works takes a lot of time and you are tempted to tinker/tweak stuff. Also I needed some data and finally I thought about ways to link Anki to my learning material. This was tempted by supermemo's incremental reading feature and this getpolarized add-on. But that's a different topic ...

I think the current form of learning steps is mostly useful for 

After this period of strictly follwing the sm orthodoxy (within Anki) I still think that some form of learning steps are very useful for some cards and that the current implementation of "fixed learning steps" that are the same for all cards is suboptimal. 

In my first post I wrote that I need intra-day learning steps for 1/2 of my new cards. That was too high. Thanks for making me pay attention to my learning process. But after these two weeks I would still say that I need these multiple steps for a substantial number of cards - maybe up 1/3? So I think this idea is still relevant. 

At the moment people use learning steps for two different purposes: "Multi-day" learning steps and "intra-day" learning steps. This post is only about the latter. 

I think the problem of "intra-day learning steps" can be divided up: 

1. Do intra-day learning steps make sense in general? 
2. If you decide to use learning steps: How should they work?
3. Is it a good idea to try to make an add-on for this: Does it cost too much time? Add-ons don't work on mobile so maybe the usefulness of such an add-on would be too limited, etc. 

&nbsp;

### intra-day learning steps are useful for some cards and situations

I can think of three justifications for intra-day learning steps:

&nbsp;

If you don't use intra-day learning steps the next interval will be at least one day. Let's say you usually review in the morning (when you are awake) and usually you learn at night. But sometimes you might not have time in the evening or want to learn more than usual. Then you also learn in the morning. If you want to achieve the same retention on the next morning it's at least conceivable that this requires an additional viewing of the material. This additional viewing on the first day would most likely be not 10 minutes later but much later in general. This later viewing should not always occur but only if the next morning is far away. So fixed learning steps don't seem like a good idea. To remedy this situation "conditional learning steps" might be useful. At the moment you could set "1 500" as learning steps. In the evening you never rate as "good" but only as "easy". But this doesn't feel elegant.

&nbsp;

On days that I use for card creation I usually start with reviews so that I'm sure that I'll finish all reviews with low intervals. Then I usually mix reviews with creating cards. This is more interesting. I dislike long uninterrupted review sessions. This improves my recall: After creating a card I always and fully know what's on it. The longer I wait until I see this card again the likelier it is that I forget the contents. I have found out that I should try to recall the cards quite quickly or I forget much more. So when creating cards usually after 10 to 20 minutes I review due cards. Then I also see the cards I created over the last 10-20 minutes. 

For many cards this one viewing is enough. In Anki I skip learning steps by pressing "easy" and graduate them to the next day. In Supermemo I rate them as "good" so that they are rescheduled at least to the next day.

But this doesn't work for all of the cards. Some of these I fail. 

In Supermemo these cards are added to the "Final Drill". after finishing all other due cards in SM you get to the final drill. You see cards in it as long as you don't rate them as good. If you have only a few cards in the final drill queue you might see the same card within a couple of seconds. You can remove a card from the "Final Drill" by rating it as "good". This immediately graduates it to the next day.

For me this increase in interval length is too much for these difficult cards: I go from a couple of minutes or even seconds to a full day. This might be a hundredfold increase in length.

You could argue that the problem is really with my cards and that they are too difficult or that I should have tried to find a visualization or mnemonic to remember the card better. In some/many cases this is true.

But this objection does not always apply. When learning something new there is a kind of "chicken or the egg" problem: 

You can only understand and easily remember single facts if you know the whole. If you know the whole (apart from the one fact on your card) reading the card makes immediate sense and without thinking much you remember it. 

But to know the whole you must start from single facts. And learning these inital facts sometimes feels more like learning random syllables. After some hours I will have learned enough context so that the first cards no longer feel like random information. Then they will make sense because I have context. Because of this context future reviews of these first cards will be easier. So the problem is not really with these cards but the fact that these are isolated cards in a new area. I could make different and even shorter cards or invest much time to find a mnemonic. But all of this wouldn't help me in the long run or it might even hurt because reviewing cards that are too easy is boring. For me it saves time in the long run to just review these initial cards more often which means with multiple learning steps on the same day. 

I have other cards in a related but different situation. I often need to learn stuff "In situation X you should think of these X things" where X usually is between two and three. These things are often not part of some checklist that I can use. But after studying about 30 or 100 similar situations I usually get a feeling of what things are relevant so that remembering these gets easier in the long run. This more or less automatically happens. 

I think I often have an idea during reviews which card should get additional reviews during the first day.

&nbsp;

Anki's/SM's algorithm was designed with the minimum information principle in mind. Many people don't fully apply the minimum information principle but make long cards that are difficult to remember in full. They might find that when reviewing a card on the next day they forget too much. Ideally they would learn to make better cards but this is unlikely to happen and the second-best alternative of multiple intra-day learning steps is still better than not using Anki at all.


### Should Intra-day learning steps be flexible?

If you accept that sometimes intra day learning steps are useful you should not use fixed learning steps because of the problems I laid out in my first post under 1-3. 

### Should an add-on be created for this?

If you don't see the problem that I see you probably shouldn't waste time on this. I should probably invest some time because I feel so strong that I open long and uninvited issues ...

**Comment by lovac42** [comment]
I pushed a new version that allows changing factors on new cards. Anki resets new cards stats once it graduates, so this wouldn't be a problem. The Pimsleur algorithm was something I wanted to test out, the code happens to mix well with your idea for dynamic learning steps, so I mixed them together.

I tested this for a few days with difficult language material and changing ease factors per card around 4-5x. I would say that this may be a good way to prime new and difficult materials. My reviews doubled,  but because the lapses are less, more new cards are added, reviewed, and spread out evenly. Weather this will have any impact on long term retention is unknown.

The learning steps I used are: 51440 7200 36000. If you want it to work on mobile, you should add some numbers between them. The addon activates once you lapse a new card (type 0 or Q3). The last learning step is the cutoff point to graduate the card. So after 36000 or 25 days, the graduating interval of 10 days will be added to the last steps plus any extra time overdues for a total of 35-45 days. In other words, after graduating a new learning card, there will be a 40 days pause before retesting as a review card.

Button operations are as follows:
Btn1: again (40% or current ivl capped at 6hrs max?)
Btn2: 80% of next ivl - 250 ef
Btn3: 100% of next ivl
Btn4: 160% of next ivl + 150 ef

Don't worry about the larger ease bonus, as we are dealing with seconds and minutes here.

**Comment by ijgnd** [comment]
Thanks for answering and your explanation. This really helped. I'm already experimenting. Your work is just amazing.
